version: "3"

services:
  redis:
    image: "redis:7-alpine"
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"

  assignment:
    container_name: api
    restart: unless-stopped
    depends_on:
      - redis
      - db
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - "./:/var/www"
    ports:
      - 3000:3000
    environment:
      - DATABASE_HOST=db

  db:
    image: 'postgres:15.2-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - assignment
    ports:
      - 80:80
      - 443:443

volumes:
  redis:
  postgres:
